In [1]:
%pip install mojito2 python-dotenv pandas pymysql mysql-connector-python sqlalchemy

Requirement already satisfied: mojito2 in c:\users\student\documents\stock-report-data-generator\stock-info\lib\site-packages (0.1.6)
Requirement already satisfied: python-dotenv in c:\users\student\documents\stock-report-data-generator\stock-info\lib\site-packages (1.0.1)
Requirement already satisfied: pandas in c:\users\student\documents\stock-report-data-generator\stock-info\lib\site-packages (2.2.3)
Requirement already satisfied: pymysql in c:\users\student\documents\stock-report-data-generator\stock-info\lib\site-packages (1.1.1)
Requirement already satisfied: mysql-connector-python in c:\users\student\documents\stock-report-data-generator\stock-info\lib\site-packages (9.0.0)
Requirement already satisfied: sqlalchemy in c:\users\student\documents\stock-report-data-generator\stock-info\lib\site-packages (2.0.35)
Requirement already satisfied: requests in c:\users\student\documents\stock-report-data-generator\stock-info\lib\site-packages (from mojito2) (2.32.3)
Requirement already satisfied: websockets in c:\users\student\documents\stock-report-data-generator\stock-info\lib\site-packages (from mojito2) (13.1)
Requirement already satisfied: pycryptodome in c:\users\student\documents\stock-report-data-generator\stock-info\lib\site-packages (from mojito2) (3.20.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\student\documents\stock-report-data-generator\stock-info\lib\site-packages (from pandas) (2.1.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\student\documents\stock-report-data-generator\stock-info\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\student\documents\stock-report-data-generator\stock-info\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\student\documents\stock-report-data-generator\stock-info\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\student\documents\stock-report-data-generator\stock-info\lib\site-packages (from sqlalchemy) (4.12.2)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\student\documents\stock-report-data-generator\stock-info\lib\site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: six>=1.5 in c:\users\student\documents\stock-report-data-generator\stock-info\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\student\documents\stock-report-data-generator\stock-info\lib\site-packages (from requests->mojito2) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\student\documents\stock-report-data-generator\stock-info\lib\site-packages (from requests->mojito2) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\student\documents\stock-report-data-generator\stock-info\lib\site-packages (from requests->mojito2) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\student\documents\stock-report-data-generator\stock-info\lib\site-packages (from requests->mojito2) (2024.8.30)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import os
from dotenv import load_dotenv
import requests
import json

load_dotenv()

KIS_APP_KEY = os.getenv("KIS_APP_KEY")
KIS_APP_SECRET = os.getenv("KIS_APP_SECRET")
KIS_ACC_NO = os.getenv("KIS_ACC_NO")
DB_HOST = os.getenv("DB_HOST")
DB_USERNAME = os.getenv("DB_USERNAME")
DB_PASSWORD = os.getenv("DB_PASSWORD")
DB_SCHEME = os.getenv("DB_SCHEME")

In [3]:
import mojito

broker = mojito.KoreaInvestment(
    api_key=KIS_APP_KEY,
    api_secret=KIS_APP_SECRET,
    acc_no=KIS_ACC_NO
)

In [4]:
import pandas as pd

# pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

pd.reset_option('display.max_rows', None)
# pd.reset_option('display.max_columns', None)

In [5]:
symbols_kospi = broker.fetch_kospi_symbols()
symbols_kospi[symbols_kospi['그룹코드'] == 'ST' ]

,단축코드,표준코드,한글명,그룹코드,시가총액규모,지수업종대분류,지수업종중분류,지수업종소분류,제조업,저유동성,지배구조지수종목,KOSPI200섹터업종,KOSPI100,KOSPI50,KRX,ETP,ELW발행,KRX100,KRX자동차,KRX반도체,KRX바이오,KRX은행,SPAC,KRX에너지화학,KRX철강,단기과열,KRX미디어통신,KRX건설,Non1,KRX증권,KRX선박,KRX섹터_보험,KRX섹터_운송,SRI,기준가,매매수량단위,시간외수량단위,거래정지,정리매매,관리종목,시장경고,경고예고,불성실공시,우회상장,락구분,액면변경,증자구분,증거금비율,신용가능,신용기간,전일거래량,액면가,상장일자,상장주수,자본금,결산월,공모가,우선주,공매도과열,이상급등,KRX300,KOSPI,매출액,영업이익,경상이익,당기순이익,ROE,기준년월,시가총액,그룹사코드,회사신용한도초과,담보대출가능,대주가능
103,000020,KR7000020008,동화약품,ST,3.0,0,9,0,Y,N,N,0,N,N,Y,NaN,N,N,N,N,Y,N,N,N,N,0,N,N,N,N,N,N,N,N,7710,1,1,N,N,N,0,N,N,N,0,0,0,60,Y,90,64910,1000,19760324,27931,27931470000,12.0,NaN,0,NaN,N,N,Y,2340,112,97,60,3.49,20240630.0,2153,NaN,N,N,N
104,000040,KR7000040006,KR모터스,ST,3.0,0,15,0,Y,N,N,0,N,N,N,NaN,N,N,N,N,N,N,N,N,N,0,N,N,N,N,N,N,N,N,568,1,1,N,N,N,0,N,N,N,0,0,0,100,N,90,113872,500,19760525,60132,30066434000,12.0,NaN,0,NaN,N,N,Y,336,-80,-106,-106,-59.34,20240630.0,341,NaN,N,N,N
105,000050,KR7000050005,경방,ST,3.0,0,16,0,N,N,N,0,N,N,N,NaN,N,N,N,N,N,N,N,N,N,0,N,N,N,N,N,N,N,N,6320,1,1,N,N,N,0,N,N,N,0,0,0,100,N,90,2561,500,19560303,27415,13707635000,12.0,NaN,0,NaN,N,N,Y,1930,134,71,46,1.25,20240630.0,1732,NaN,N,N,N
106,000070,KR7000070003,삼양홀딩스,ST,2.0,0,21,0,N,N,N,0,N,N,N,NaN,N,N,N,N,N,N,N,N,N,0,N,N,N,N,N,N,N,N,79100,1,1,N,N,N,0,N,N,N,0,0,0,40,Y,90,25136,5000,19681227,8564,42821355000,12.0,NaN,0,NaN,N,N,Y,17885,899,1072,839,4.50,20240630.0,6774,NaN,N,N,N
107,000075,KR7000071001,삼양홀딩스우,ST,0.0,0,21,0,N,Y,N,0,N,N,N,NaN,N,N,N,N,N,N,N,N,N,0,N,N,N,N,N,N,N,N,56700,1,1,N,N,Y,0,N,N,N,0,0,0,100,N,90,30,5000,19920221,304,1520290000,12.0,NaN,1,NaN,N,N,N,0,0,0,0,0.00,NaN,172,NaN,N,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1753,462520,KR7462520008,조선내화,ST,3.0,0,10,0,Y,N,NaN,0,N,N,N,NaN,N,N,NaN,NaN,NaN,NaN,N,NaN,NaN,0,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,17100,1,1,N,N,N,0,N,N,N,0,0,0,60,Y,90,20447,500,20230728,11855,5927584000,12.0,NaN,0,NaN,N,N,Y,2534,130,112,77,7.05,20240630.0,2027,NaN,N,N,N
1755,462870,KR7462870007,시프트업,ST,0.0,0,26,0,N,N,NaN,0,N,N,N,NaN,N,N,NaN,NaN,NaN,NaN,N,NaN,NaN,0,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,57200,1,1,N,N,N,0,N,N,N,0,0,0,100,N,90,122965,200,20240711,58334,11666944000,12.0,NaN,0,NaN,N,N,Y,1686,1111,1143,1067,99.16,20231231.0,33367,NaN,N,N,N
1782,465770,KR7465770006,STX그린로지스,ST,3.0,0,19,0,N,N,NaN,0,N,N,N,NaN,N,N,NaN,NaN,NaN,NaN,N,NaN,NaN,0,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,14450,1,1,N,N,N,0,N,N,N,0,0,0,100,N,90,3259288,2500,20230915,7171,17927580000,12.0,NaN,0,NaN,N,N,Y,218,36,34,34,20.26,20240630.0,1036,NaN,N,N,N
1845,475150,KR7475150009,SK이터닉스,ST,2.0,0,18,0,N,N,NaN,0,N,N,N,NaN,N,N,NaN,NaN,NaN,NaN,N,NaN,NaN,0,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,18400,1,1,N,N,N,0,N,N,N,0,0,0,100,N,90,1692715,200,20240329,33691,6738379000,12.0,NaN,0,NaN,N,N,Y,188,-19,-34,-41,0.00,20240630.0,6199,535,N,N,N
1921,487570,KR7487570004,HS효성,ST,3.0,0,21,0,N,N,NaN,0,N,N,Y,NaN,N,N,NaN,NaN,NaN,NaN,N,NaN,NaN,0,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,41750,1,1,N,N,N,0,N,N,N,0,0,0,100,N,90,5994,5000,20240729,3725,18629635000,12.0,NaN,0,NaN,N,Y,Y,0,0,0,0,0.00,NaN,1555,971,N,N,N

In [6]:
symbols_kosdaq = broker.fetch_kosdaq_symbols()
symbols_kosdaq[symbols_kosdaq['그룹코드'] == 'ST']

,단축코드,표준코드,한글명,그룹코드,시가총액규모,지수업종대분류,지수업종중분류,지수업종소분류,벤처기업,저유동성,KRX,ETP,KRX100,KRX자동차,KRX반도체,KRX바이오,KRX은행,SPAC,KRX에너지화학,KRX철강,단기과열,KRX미디어통신,KRX건설,투자주의,KRX증권,KRX선박,KRX섹터_보험,KRX섹터_운송,KOSDAQ150,기준가,매매수량단위,시간외수량단위,거래정지,정리매매,관리종목,시장경고,경고예고,불성실공시,우회상장,락구분,액면변경,증자구분,증거금비율,신용가능,신용기간,전일거래량,액면가,상장일자,상장주수,자본금,결산월,공모가,우선주,공매도과열,이상급등,KRX300,매출액,영업이익,경상이익,당기순이익,ROE,기준년월,시가총액,그룹사코드,회사신용한도초과,담보대출가능,대주가능
7,000250,KR7000250001,삼천당제약,ST,1.0,0,1009,1024,N,N,Y,NaN,N,N,N,N,N,N,N,N,0,N,N,N,N,N,N,N,Y,131300,1,1,N,N,N,0,N,N,N,0,0,0,100,N,90,523127,500,20001004,23457,11728736000,12,NaN,0,NaN,N,Y,1033,40,72,41,1,20240630.0,30799,NaN,N,N,N
8,000440,KR7000440008,중앙에너비스,ST,3.0,0,1011,0,N,N,N,NaN,N,N,N,N,N,N,N,N,0,N,N,N,N,N,N,N,N,21600,1,1,N,N,N,0,N,N,N,0,0,0,100,N,90,110375,500,19930324,6227,3113565000,12,NaN,0,NaN,N,N,230,-15,-13,-13,-5,20240630.0,1345,NaN,N,N,N
9,001000,KR7001000009,신라섬유,ST,3.0,1006,0,0,N,N,N,NaN,N,N,N,N,N,N,N,N,0,N,N,N,N,N,N,N,N,1153,1,1,N,N,N,0,N,N,N,0,0,0,100,N,90,334200,100,19940628,24277,2427754000,12,NaN,0,NaN,N,N,38,4,-4,-7,-4,20231231.0,279,NaN,N,N,N
10,001540,KR7001540004,안국약품,ST,3.0,0,1009,1024,N,N,Y,NaN,N,N,N,Y,N,N,N,N,0,N,N,N,N,N,N,N,N,7240,1,1,N,N,N,0,N,N,N,0,0,0,100,N,90,10096,500,20000615,13042,6521210000,12,NaN,0,NaN,N,N,1329,47,224,174,22,20240630.0,944,NaN,N,N,N
11,001810,KR7001810001,무림SP,ST,3.0,0,1009,1021,N,N,N,NaN,N,N,N,N,N,N,N,N,0,N,N,N,N,N,N,N,N,1656,1,1,N,N,N,0,N,N,N,0,0,0,100,N,90,7525,500,20000104,22137,11068750000,12,NaN,0,NaN,N,N,882,10,48,41,4,20240630.0,366,NaN,N,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1737,479880,KR7479880007,한국제15호스팩,ST,0.0,0,1014,0,NaN,N,N,NaN,N,NaN,NaN,NaN,NaN,Y,NaN,NaN,0,NaN,NaN,N,NaN,NaN,NaN,NaN,N,2035,1,1,N,N,N,0,N,N,N,0,0,0,100,N,90,33485,100,20240626,6870,687000000,12,NaN,0,NaN,N,N,0,0,0,0,0,NaN,139,NaN,N,N,N
1738,481890,KR7481890002,엔에이치스팩31호,ST,0.0,0,1014,0,NaN,N,N,NaN,N,NaN,NaN,NaN,NaN,Y,NaN,NaN,0,NaN,NaN,N,NaN,NaN,NaN,NaN,N,2025,1,1,N,N,N,0,N,N,N,0,0,0,100,N,90,32254,100,20240726,6345,634500000,12,NaN,0,NaN,N,N,0,0,0,0,0,NaN,128,NaN,N,N,N
1739,482520,KR7482520004,교보16호스팩,ST,0.0,0,1014,0,NaN,N,N,NaN,N,NaN,NaN,NaN,NaN,Y,NaN,NaN,0,NaN,NaN,N,NaN,NaN,NaN,NaN,N,2040,1,1,N,N,N,0,N,N,N,0,0,0,100,N,90,11458,100,20240813,6100,610000000,12,NaN,0,NaN,N,N,0,0,0,0,0,NaN,124,NaN,N,N,N
1740,482680,KR7482680006,미래에셋비전스팩7호,ST,0.0,0,1014,0,NaN,N,N,NaN,N,NaN,NaN,NaN,NaN,Y,NaN,NaN,0,NaN,NaN,N,NaN,NaN,NaN,NaN,N,1985,1,1,N,N,N,0,N,N,N,0,0,0,100,N,90,157385,100,20240911,8215,821500000,12,NaN,0,NaN,N,N,0,0,0,0,0,NaN,163,NaN,N,N,N
1741,486630,KR7486630007,KB제30호스팩,ST,0.0,0,1014,0,NaN,N,N,NaN,N,NaN,NaN,NaN,NaN,Y,NaN,NaN,0,NaN,NaN,N,NaN,NaN,NaN,NaN,N,2005,1,1,N,N,N,0,N,N,N,0,0,0,100,N,90,50746084,100,20240925,5310,531000000,12,NaN,0,NaN,N,N,0,0,0,0,0,NaN,106,NaN,N,N,N

In [7]:
filtered_kospi = symbols_kospi[symbols_kospi['그룹코드'] == 'ST']
filtered_kosdaq = symbols_kosdaq[symbols_kosdaq['그룹코드'] == 'ST']

# 두 DataFrame 합치기
combined_symbols = pd.concat([filtered_kospi, filtered_kosdaq])

# 값 치환 (N -> S, Y -> A)
combined_symbols['거래정지'] = combined_symbols['거래정지'].replace({'N': 'S', 'Y': 'A'})
columns_to_keep = ['단축코드', '한글명', '표준코드', '시가총액', '거래정지']

combined_symbols = combined_symbols[columns_to_keep]

combined_symbols

        단축코드         한글명          표준코드  시가총액 거래정지
103   000020        동화약품  KR7000020008  2153    S
104   000040       KR모터스  KR7000040006   341    S
105   000050          경방  KR7000050005  1732    S
106   000070       삼양홀딩스  KR7000070003  6774    S
107   000075      삼양홀딩스우  KR7000071001   172    S
...      ...         ...           ...   ...  ...
1737  479880    한국제15호스팩  KR7479880007   139    S
1738  481890   엔에이치스팩31호  KR7481890002   128    S
1739  482520     교보16호스팩  KR7482520004   124    S
1740  482680  미래에셋비전스팩7호  KR7482680006   163    S
1741  486630    KB제30호스팩  KR7486630007   106    S

[2663 rows x 5 columns]

In [8]:
duplicated_shortcodes = combined_symbols[combined_symbols['단축코드'].duplicated(keep=False)]

# 중복된 값이 있는지 여부 확인
if not duplicated_shortcodes.empty:
    print("중복된 shortcode가 존재합니다:")
    print(duplicated_shortcodes)
else:
    print("중복된 shortcode가 없습니다.")

중복된 shortcode가 없습니다.

In [9]:
combined_symbols.to_csv("stock_info.csv", index=True, encoding="utf-8-sig")

In [10]:
import pymysql

# MySQL 연결 설정
connection = pymysql.connect(
    host=DB_HOST,     # MySQL 서버 주소
    user=DB_USERNAME,       # MySQL 사용자 이름
    password=DB_PASSWORD,   # MySQL 비밀번호
    database=DB_SCHEME    # 사용할 데이터베이스 이름
)

In [11]:
# SQL 쿼리 실행
cursor = connection.cursor()

# cursor.execute("SELECT * FROM SUB_CATEGORY")
cursor.execute('desc STOCK')
result = cursor.fetchall()

# for row in result:
    # print(row)
result

(('STOCK_ID', 'int', 'NO', 'PRI', None, 'auto_increment'),
 ('SHORT_CODE', 'varchar(6)', 'NO', 'PRI', None, ''),
 ('SUB_CATEGORY_ID', 'int', 'NO', 'MUL', None, ''),
 ('STOCK_NAME', 'varchar(10)', 'YES', '', None, ''),
 ('STANDARD_CODE', 'varchar(12)', 'NO', '', None, ''),
 ('STOCK_EXCHANGE_MARKET', 'char(1)', 'YES', '', None, ''),
 ('MARKET_CAPITALIZATION', 'varchar(10)', 'YES', '', None, ''),
 ('OPEN_PRICE', 'int', 'YES', '', None, ''),
 ('CLOSED_PRICE', 'int', 'YES', '', None, ''),
 ('HIGH_PRICE', 'int', 'YES', '', None, ''),
 ('LOW_PRICE', 'int', 'YES', '', None, ''),
 ('STOCK_TRADE_STATUS', 'char(1)', 'YES', '', None, ''),
 ('CREATED_AT',
  'timestamp',
  'YES',
  '',
  'CURRENT_TIMESTAMP',
  'DEFAULT_GENERATED'),
 ('UPDATED_AT', 'timestamp', 'YES', '', None, ''))

In [12]:
from sqlalchemy import create_engine, MetaData, Table
# MySQL 데이터베이스 연결 설정
db_username = DB_USERNAME
db_password = DB_PASSWORD
db_host = DB_HOST
db_name = DB_SCHEME

# 데이터프레임 컬럼명과 데이터베이스 컬럼명을 매핑하는 딕셔너리 생성

# SQLAlchemy 엔진 생성
engine = create_engine(f'mysql+pymysql://{db_username}:{db_password}@{db_host}/{db_name}')

# 메타데이터 객체 생성
metadata = MetaData()

table_name = 'STOCK'
table = Table(table_name, metadata, autoload_with=engine)

# 테이블 컬럼명 확인
db_columns = [column.name for column in table.columns]

db_columns

['STOCK_ID',
 'SHORT_CODE',
 'SUB_CATEGORY_ID',
 'STOCK_NAME',
 'STANDARD_CODE',
 'STOCK_EXCHANGE_MARKET',
 'MARKET_CAPITALIZATION',
 'OPEN_PRICE',
 'CLOSED_PRICE',
 'HIGH_PRICE',
 'LOW_PRICE',
 'STOCK_TRADE_STATUS',
 'CREATED_AT',
 'UPDATED_AT']

In [13]:
column_mapping = {
    '단축코드': 'SHORT_CODE',
    '서브카테고리' : 'SUB_CATEGORY_ID',
    '한글명': 'STOCK_NAME',
    '표준코드': 'STANDARD_CODE',
    '거래소': 'STOCK_EXCHANGE_MARKET',
    '시가총액': 'MARKET_CAPITALIZATION',
    '시가': 'OPEN_PRICE',
    '종가': 'CLOSED_PRICE',
    '고가': 'HIGH_PRICE',
    '저가': 'LOW_PRICE',
    '거래정지': 'STOCK_TRADE_STATUS',
}

# 컬럼명 매핑 적용
combined_symbols.rename(columns=column_mapping, inplace=True)

In [14]:
for column in [
 'SHORT_CODE',
 'SUB_CATEGORY_ID',
 'STOCK_NAME',
 'STANDARD_CODE',
 'STOCK_EXCHANGE_MARKET',
 'MARKET_CAPITALIZATION',
 'OPEN_PRICE',
 'CLOSED_PRICE',
 'HIGH_PRICE',
 'LOW_PRICE',
 'STOCK_TRADE_STATUS']:
    if column not in combined_symbols.columns:
        combined_symbols[column] = 1

In [15]:
combined_symbols

,SHORT_CODE,STOCK_NAME,STANDARD_CODE,MARKET_CAPITALIZATION,STOCK_TRADE_STATUS,SUB_CATEGORY_ID,STOCK_EXCHANGE_MARKET,OPEN_PRICE,CLOSED_PRICE,HIGH_PRICE,LOW_PRICE
103,000020,동화약품,KR7000020008,2153,S,1,1,1,1,1,1
104,000040,KR모터스,KR7000040006,341,S,1,1,1,1,1,1
105,000050,경방,KR7000050005,1732,S,1,1,1,1,1,1
106,000070,삼양홀딩스,KR7000070003,6774,S,1,1,1,1,1,1
107,000075,삼양홀딩스우,KR7000071001,172,S,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...
1737,479880,한국제15호스팩,KR7479880007,139,S,1,1,1,1,1,1
1738,481890,엔에이치스팩31호,KR7481890002,128,S,1,1,1,1,1,1
1739,482520,교보16호스팩,KR7482520004,124,S,1,1,1,1,1,1
1740,482680,미래에셋비전스팩7호,KR7482680006,163,S,1,1,1,1,1,1
1741,486630,KB제30호스팩,KR7486630007,106,S,1,1,1,1,1,1

In [16]:
combined_symbols

,SHORT_CODE,STOCK_NAME,STANDARD_CODE,MARKET_CAPITALIZATION,STOCK_TRADE_STATUS,SUB_CATEGORY_ID,STOCK_EXCHANGE_MARKET,OPEN_PRICE,CLOSED_PRICE,HIGH_PRICE,LOW_PRICE
103,000020,동화약품,KR7000020008,2153,S,1,1,1,1,1,1
104,000040,KR모터스,KR7000040006,341,S,1,1,1,1,1,1
105,000050,경방,KR7000050005,1732,S,1,1,1,1,1,1
106,000070,삼양홀딩스,KR7000070003,6774,S,1,1,1,1,1,1
107,000075,삼양홀딩스우,KR7000071001,172,S,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...
1737,479880,한국제15호스팩,KR7479880007,139,S,1,1,1,1,1,1
1738,481890,엔에이치스팩31호,KR7481890002,128,S,1,1,1,1,1,1
1739,482520,교보16호스팩,KR7482520004,124,S,1,1,1,1,1,1
1740,482680,미래에셋비전스팩7호,KR7482680006,163,S,1,1,1,1,1,1
1741,486630,KB제30호스팩,KR7486630007,106,S,1,1,1,1,1,1

In [19]:
combined_symbols.iloc[10:100].to_sql(name='STOCK', con=engine, if_exists='append', index=False)

90