In [1]:
%pip install mojito2 python-dotenv pandas pymysql mysql-connector-python sqlalchemy

Requirement already satisfied: mojito2 in c:\users\student\documents\stock-report-data-generator\stock-info\lib\site-packages (0.1.6)
Requirement already satisfied: python-dotenv in c:\users\student\documents\stock-report-data-generator\stock-info\lib\site-packages (1.0.1)
Requirement already satisfied: pandas in c:\users\student\documents\stock-report-data-generator\stock-info\lib\site-packages (2.2.3)
Requirement already satisfied: pymysql in c:\users\student\documents\stock-report-data-generator\stock-info\lib\site-packages (1.1.1)
Requirement already satisfied: mysql-connector-python in c:\users\student\documents\stock-report-data-generator\stock-info\lib\site-packages (9.0.0)
Requirement already satisfied: sqlalchemy in c:\users\student\documents\stock-report-data-generator\stock-info\lib\site-packages (2.0.35)
Requirement already satisfied: requests in c:\users\student\documents\stock-report-data-generator\stock-info\lib\site-packages (from mojito2) (2.32.3)
Requirement already satisfied: websockets in c:\users\student\documents\stock-report-data-generator\stock-info\lib\site-packages (from mojito2) (13.1)
Requirement already satisfied: pycryptodome in c:\users\student\documents\stock-report-data-generator\stock-info\lib\site-packages (from mojito2) (3.20.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\student\documents\stock-report-data-generator\stock-info\lib\site-packages (from pandas) (2.1.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\student\documents\stock-report-data-generator\stock-info\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\student\documents\stock-report-data-generator\stock-info\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\student\documents\stock-report-data-generator\stock-info\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\student\documents\stock-report-data-generator\stock-info\lib\site-packages (from sqlalchemy) (4.12.2)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\student\documents\stock-report-data-generator\stock-info\lib\site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: six>=1.5 in c:\users\student\documents\stock-report-data-generator\stock-info\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\student\documents\stock-report-data-generator\stock-info\lib\site-packages (from requests->mojito2) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\student\documents\stock-report-data-generator\stock-info\lib\site-packages (from requests->mojito2) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\student\documents\stock-report-data-generator\stock-info\lib\site-packages (from requests->mojito2) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\student\documents\stock-report-data-generator\stock-info\lib\site-packages (from requests->mojito2) (2024.8.30)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import os
from dotenv import load_dotenv
import requests
import json

load_dotenv()

KIS_APP_KEY = os.getenv("KIS_APP_KEY")
KIS_APP_SECRET = os.getenv("KIS_APP_SECRET")
KIS_ACC_NO = os.getenv("KIS_ACC_NO")
DB_HOST = os.getenv("DB_HOST")
DB_USERNAME = os.getenv("DB_USERNAME")
DB_PASSWORD = os.getenv("DB_PASSWORD")
DB_SCHEME = os.getenv("DB_SCHEME")

In [3]:
import mojito

broker = mojito.KoreaInvestment(
    api_key=KIS_APP_KEY,
    api_secret=KIS_APP_SECRET,
    acc_no=KIS_ACC_NO
)

In [4]:
import pandas as pd

# pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

pd.reset_option('display.max_rows', None)
# pd.reset_option('display.max_columns', None)

In [5]:
symbols_kospi = broker.fetch_kospi_symbols()
symbols_kospi[symbols_kospi['그룹코드'] == 'ST' ]

,단축코드,표준코드,한글명,그룹코드,시가총액규모,지수업종대분류,지수업종중분류,지수업종소분류,제조업,저유동성,지배구조지수종목,KOSPI200섹터업종,KOSPI100,KOSPI50,KRX,ETP,ELW발행,KRX100,KRX자동차,KRX반도체,KRX바이오,KRX은행,SPAC,KRX에너지화학,KRX철강,단기과열,KRX미디어통신,KRX건설,Non1,KRX증권,KRX선박,KRX섹터_보험,KRX섹터_운송,SRI,기준가,매매수량단위,시간외수량단위,거래정지,정리매매,관리종목,시장경고,경고예고,불성실공시,우회상장,락구분,액면변경,증자구분,증거금비율,신용가능,신용기간,전일거래량,액면가,상장일자,상장주수,자본금,결산월,공모가,우선주,공매도과열,이상급등,KRX300,KOSPI,매출액,영업이익,경상이익,당기순이익,ROE,기준년월,시가총액,그룹사코드,회사신용한도초과,담보대출가능,대주가능
103,000020,KR7000020008,동화약품,ST,3.0,0,9,0,Y,N,N,0,N,N,Y,NaN,N,N,N,N,Y,N,N,N,N,0,N,N,N,N,N,N,N,N,7710,1,1,N,N,N,0,N,N,N,0,0,0,60,Y,90,64910,1000,19760324,27931,27931470000,12.0,NaN,0,NaN,N,N,Y,2340,112,97,60,3.49,20240630.0,2153,NaN,N,N,N
104,000040,KR7000040006,KR모터스,ST,3.0,0,15,0,Y,N,N,0,N,N,N,NaN,N,N,N,N,N,N,N,N,N,0,N,N,N,N,N,N,N,N,568,1,1,N,N,N,0,N,N,N,0,0,0,100,N,90,113872,500,19760525,60132,30066434000,12.0,NaN,0,NaN,N,N,Y,336,-80,-106,-106,-59.34,20240630.0,341,NaN,N,N,N
105,000050,KR7000050005,경방,ST,3.0,0,16,0,N,N,N,0,N,N,N,NaN,N,N,N,N,N,N,N,N,N,0,N,N,N,N,N,N,N,N,6320,1,1,N,N,N,0,N,N,N,0,0,0,100,N,90,2561,500,19560303,27415,13707635000,12.0,NaN,0,NaN,N,N,Y,1930,134,71,46,1.25,20240630.0,1732,NaN,N,N,N
106,000070,KR7000070003,삼양홀딩스,ST,2.0,0,21,0,N,N,N,0,N,N,N,NaN,N,N,N,N,N,N,N,N,N,0,N,N,N,N,N,N,N,N,79100,1,1,N,N,N,0,N,N,N,0,0,0,40,Y,90,25136,5000,19681227,8564,42821355000,12.0,NaN,0,NaN,N,N,Y,17885,899,1072,839,4.50,20240630.0,6774,NaN,N,N,N
107,000075,KR7000071001,삼양홀딩스우,ST,0.0,0,21,0,N,Y,N,0,N,N,N,NaN,N,N,N,N,N,N,N,N,N,0,N,N,N,N,N,N,N,N,56700,1,1,N,N,Y,0,N,N,N,0,0,0,100,N,90,30,5000,19920221,304,1520290000,12.0,NaN,1,NaN,N,N,N,0,0,0,0,0.00,NaN,172,NaN,N,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1753,462520,KR7462520008,조선내화,ST,3.0,0,10,0,Y,N,NaN,0,N,N,N,NaN,N,N,NaN,NaN,NaN,NaN,N,NaN,NaN,0,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,17100,1,1,N,N,N,0,N,N,N,0,0,0,60,Y,90,20447,500,20230728,11855,5927584000,12.0,NaN,0,NaN,N,N,Y,2534,130,112,77,7.05,20240630.0,2027,NaN,N,N,N
1755,462870,KR7462870007,시프트업,ST,0.0,0,26,0,N,N,NaN,0,N,N,N,NaN,N,N,NaN,NaN,NaN,NaN,N,NaN,NaN,0,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,57200,1,1,N,N,N,0,N,N,N,0,0,0,100,N,90,122965,200,20240711,58334,11666944000,12.0,NaN,0,NaN,N,N,Y,1686,1111,1143,1067,99.16,20231231.0,33367,NaN,N,N,N
1782,465770,KR7465770006,STX그린로지스,ST,3.0,0,19,0,N,N,NaN,0,N,N,N,NaN,N,N,NaN,NaN,NaN,NaN,N,NaN,NaN,0,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,14450,1,1,N,N,N,0,N,N,N,0,0,0,100,N,90,3259288,2500,20230915,7171,17927580000,12.0,NaN,0,NaN,N,N,Y,218,36,34,34,20.26,20240630.0,1036,NaN,N,N,N
1845,475150,KR7475150009,SK이터닉스,ST,2.0,0,18,0,N,N,NaN,0,N,N,N,NaN,N,N,NaN,NaN,NaN,NaN,N,NaN,NaN,0,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,18400,1,1,N,N,N,0,N,N,N,0,0,0,100,N,90,1692715,200,20240329,33691,6738379000,12.0,NaN,0,NaN,N,N,Y,188,-19,-34,-41,0.00,20240630.0,6199,535,N,N,N
1921,487570,KR7487570004,HS효성,ST,3.0,0,21,0,N,N,NaN,0,N,N,Y,NaN,N,N,NaN,NaN,NaN,NaN,N,NaN,NaN,0,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,41750,1,1,N,N,N,0,N,N,N,0,0,0,100,N,90,5994,5000,20240729,3725,18629635000,12.0,NaN,0,NaN,N,Y,Y,0,0,0,0,0.00,NaN,1555,971,N,N,N

In [6]:
symbols_kosdaq = broker.fetch_kosdaq_symbols()
symbols_kosdaq[symbols_kosdaq['그룹코드'] == 'ST']

,단축코드,표준코드,한글명,그룹코드,시가총액규모,지수업종대분류,지수업종중분류,지수업종소분류,벤처기업,저유동성,KRX,ETP,KRX100,KRX자동차,KRX반도체,KRX바이오,KRX은행,SPAC,KRX에너지화학,KRX철강,단기과열,KRX미디어통신,KRX건설,투자주의,KRX증권,KRX선박,KRX섹터_보험,KRX섹터_운송,KOSDAQ150,기준가,매매수량단위,시간외수량단위,거래정지,정리매매,관리종목,시장경고,경고예고,불성실공시,우회상장,락구분,액면변경,증자구분,증거금비율,신용가능,신용기간,전일거래량,액면가,상장일자,상장주수,자본금,결산월,공모가,우선주,공매도과열,이상급등,KRX300,매출액,영업이익,경상이익,당기순이익,ROE,기준년월,시가총액,그룹사코드,회사신용한도초과,담보대출가능,대주가능
7,000250,KR7000250001,삼천당제약,ST,1.0,0,1009,1024,N,N,Y,NaN,N,N,N,N,N,N,N,N,0,N,N,N,N,N,N,N,Y,131300,1,1,N,N,N,0,N,N,N,0,0,0,100,N,90,523127,500,20001004,23457,11728736000,12,NaN,0,NaN,N,Y,1033,40,72,41,1,20240630.0,30799,NaN,N,N,N
8,000440,KR7000440008,중앙에너비스,ST,3.0,0,1011,0,N,N,N,NaN,N,N,N,N,N,N,N,N,0,N,N,N,N,N,N,N,N,21600,1,1,N,N,N,0,N,N,N,0,0,0,100,N,90,110375,500,19930324,6227,3113565000,12,NaN,0,NaN,N,N,230,-15,-13,-13,-5,20240630.0,1345,NaN,N,N,N
9,001000,KR7001000009,신라섬유,ST,3.0,1006,0,0,N,N,N,NaN,N,N,N,N,N,N,N,N,0,N,N,N,N,N,N,N,N,1153,1,1,N,N,N,0,N,N,N,0,0,0,100,N,90,334200,100,19940628,24277,2427754000,12,NaN,0,NaN,N,N,38,4,-4,-7,-4,20231231.0,279,NaN,N,N,N
10,001540,KR7001540004,안국약품,ST,3.0,0,1009,1024,N,N,Y,NaN,N,N,N,Y,N,N,N,N,0,N,N,N,N,N,N,N,N,7240,1,1,N,N,N,0,N,N,N,0,0,0,100,N,90,10096,500,20000615,13042,6521210000,12,NaN,0,NaN,N,N,1329,47,224,174,22,20240630.0,944,NaN,N,N,N
11,001810,KR7001810001,무림SP,ST,3.0,0,1009,1021,N,N,N,NaN,N,N,N,N,N,N,N,N,0,N,N,N,N,N,N,N,N,1656,1,1,N,N,N,0,N,N,N,0,0,0,100,N,90,7525,500,20000104,22137,11068750000,12,NaN,0,NaN,N,N,882,10,48,41,4,20240630.0,366,NaN,N,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1737,479880,KR7479880007,한국제15호스팩,ST,0.0,0,1014,0,NaN,N,N,NaN,N,NaN,NaN,NaN,NaN,Y,NaN,NaN,0,NaN,NaN,N,NaN,NaN,NaN,NaN,N,2035,1,1,N,N,N,0,N,N,N,0,0,0,100,N,90,33485,100,20240626,6870,687000000,12,NaN,0,NaN,N,N,0,0,0,0,0,NaN,139,NaN,N,N,N
1738,481890,KR7481890002,엔에이치스팩31호,ST,0.0,0,1014,0,NaN,N,N,NaN,N,NaN,NaN,NaN,NaN,Y,NaN,NaN,0,NaN,NaN,N,NaN,NaN,NaN,NaN,N,2025,1,1,N,N,N,0,N,N,N,0,0,0,100,N,90,32254,100,20240726,6345,634500000,12,NaN,0,NaN,N,N,0,0,0,0,0,NaN,128,NaN,N,N,N
1739,482520,KR7482520004,교보16호스팩,ST,0.0,0,1014,0,NaN,N,N,NaN,N,NaN,NaN,NaN,NaN,Y,NaN,NaN,0,NaN,NaN,N,NaN,NaN,NaN,NaN,N,2040,1,1,N,N,N,0,N,N,N,0,0,0,100,N,90,11458,100,20240813,6100,610000000,12,NaN,0,NaN,N,N,0,0,0,0,0,NaN,124,NaN,N,N,N
1740,482680,KR7482680006,미래에셋비전스팩7호,ST,0.0,0,1014,0,NaN,N,N,NaN,N,NaN,NaN,NaN,NaN,Y,NaN,NaN,0,NaN,NaN,N,NaN,NaN,NaN,NaN,N,1985,1,1,N,N,N,0,N,N,N,0,0,0,100,N,90,157385,100,20240911,8215,821500000,12,NaN,0,NaN,N,N,0,0,0,0,0,NaN,163,NaN,N,N,N
1741,486630,KR7486630007,KB제30호스팩,ST,0.0,0,1014,0,NaN,N,N,NaN,N,NaN,NaN,NaN,NaN,Y,NaN,NaN,0,NaN,NaN,N,NaN,NaN,NaN,NaN,N,2005,1,1,N,N,N,0,N,N,N,0,0,0,100,N,90,50746084,100,20240925,5310,531000000,12,NaN,0,NaN,N,N,0,0,0,0,0,NaN,106,NaN,N,N,N

In [7]:
filtered_kospi = symbols_kospi[symbols_kospi['그룹코드'] == 'ST']
filtered_kosdaq = symbols_kosdaq[symbols_kosdaq['그룹코드'] == 'ST']

# 두 DataFrame 합치기
combined_symbols = pd.concat([filtered_kospi, filtered_kosdaq])

# 값 치환 (N -> S, Y -> A)
combined_symbols['거래정지'] = combined_symbols['거래정지'].replace({'N': 'S', 'Y': 'A'})
columns_to_keep = ['단축코드', '한글명', '표준코드', '시가총액', '거래정지']

combined_symbols = combined_symbols[columns_to_keep]

combined_symbols

        단축코드         한글명          표준코드  시가총액 거래정지
103   000020        동화약품  KR7000020008  2153    S
104   000040       KR모터스  KR7000040006   341    S
105   000050          경방  KR7000050005  1732    S
106   000070       삼양홀딩스  KR7000070003  6774    S
107   000075      삼양홀딩스우  KR7000071001   172    S
...      ...         ...           ...   ...  ...
1737  479880    한국제15호스팩  KR7479880007   139    S
1738  481890   엔에이치스팩31호  KR7481890002   128    S
1739  482520     교보16호스팩  KR7482520004   124    S
1740  482680  미래에셋비전스팩7호  KR7482680006   163    S
1741  486630    KB제30호스팩  KR7486630007   106    S

[2663 rows x 5 columns]

In [8]:
duplicated_shortcodes = combined_symbols[combined_symbols['단축코드'].duplicated(keep=False)]

# 중복된 값이 있는지 여부 확인
if not duplicated_shortcodes.empty:
    print("중복된 shortcode가 존재합니다:")
    print(duplicated_shortcodes)
else:
    print("중복된 shortcode가 없습니다.")

중복된 shortcode가 없습니다.

In [9]:
combined_symbols.to_csv("stock_info.csv", index=True, encoding="utf-8-sig")

In [10]:
import pymysql

# MySQL 연결 설정
connection = pymysql.connect(
    host=DB_HOST,     # MySQL 서버 주소
    user=DB_USERNAME,       # MySQL 사용자 이름
    password=DB_PASSWORD,   # MySQL 비밀번호
    database=DB_SCHEME    # 사용할 데이터베이스 이름
)

In [11]:
# SQL 쿼리 실행
cursor = connection.cursor()

# cursor.execute("SELECT * FROM SUB_CATEGORY")
cursor.execute('desc STOCK')
result = cursor.fetchall()

# for row in result:
    # print(row)
result

(('STOCK_ID', 'int', 'NO', 'PRI', None, 'auto_increment'),
 ('SHORT_CODE', 'varchar(6)', 'NO', 'PRI', None, ''),
 ('SUB_CATEGORY_ID', 'int', 'NO', 'MUL', None, ''),
 ('STOCK_NAME', 'varchar(10)', 'YES', '', None, ''),
 ('STANDARD_CODE', 'varchar(12)', 'NO', '', None, ''),
 ('STOCK_EXCHANGE_MARKET', 'char(1)', 'YES', '', None, ''),
 ('MARKET_CAPITALIZATION', 'varchar(10)', 'YES', '', None, ''),
 ('OPEN_PRICE', 'int', 'YES', '', None, ''),
 ('CLOSED_PRICE', 'int', 'YES', '', None, ''),
 ('HIGH_PRICE', 'int', 'YES', '', None, ''),
 ('LOW_PRICE', 'int', 'YES', '', None, ''),
 ('STOCK_TRADE_STATUS', 'char(1)', 'YES', '', None, ''),
 ('CREATED_AT',
  'timestamp',
  'YES',
  '',
  'CURRENT_TIMESTAMP',
  'DEFAULT_GENERATED'),
 ('UPDATED_AT', 'timestamp', 'YES', '', None, ''))

In [12]:
from sqlalchemy import create_engine, MetaData, Table
# MySQL 데이터베이스 연결 설정
db_username = DB_USERNAME
db_password = DB_PASSWORD
db_host = DB_HOST
db_name = DB_SCHEME

# 데이터프레임 컬럼명과 데이터베이스 컬럼명을 매핑하는 딕셔너리 생성

# SQLAlchemy 엔진 생성
engine = create_engine(f'mysql+pymysql://{db_username}:{db_password}@{db_host}/{db_name}')

# 메타데이터 객체 생성
metadata = MetaData()

table_name = 'STOCK'
table = Table(table_name, metadata, autoload_with=engine)

# 테이블 컬럼명 확인
db_columns = [column.name for column in table.columns]

db_columns

['STOCK_ID',
 'SHORT_CODE',
 'SUB_CATEGORY_ID',
 'STOCK_NAME',
 'STANDARD_CODE',
 'STOCK_EXCHANGE_MARKET',
 'MARKET_CAPITALIZATION',
 'OPEN_PRICE',
 'CLOSED_PRICE',
 'HIGH_PRICE',
 'LOW_PRICE',
 'STOCK_TRADE_STATUS',
 'CREATED_AT',
 'UPDATED_AT']

In [13]:
column_mapping = {
    '단축코드': 'SHORT_CODE',
    '서브카테고리' : 'SUB_CATEGORY_ID',
    '한글명': 'STOCK_NAME',
    '표준코드': 'STANDARD_CODE',
    '거래소': 'STOCK_EXCHANGE_MARKET',
    '시가총액': 'MARKET_CAPITALIZATION',
    '시가': 'OPEN_PRICE',
    '종가': 'CLOSED_PRICE',
    '고가': 'HIGH_PRICE',
    '저가': 'LOW_PRICE',
    '거래정지': 'STOCK_TRADE_STATUS',
}

# 컬럼명 매핑 적용
combined_symbols.rename(columns=column_mapping, inplace=True)

In [14]:
for column in db_columns:
    if column not in combined_symbols.columns:
        combined_symbols[column] = 1

In [15]:
combined_symbols

,SHORT_CODE,STOCK_NAME,STANDARD_CODE,MARKET_CAPITALIZATION,STOCK_TRADE_STATUS,STOCK_ID,SUB_CATEGORY_ID,STOCK_EXCHANGE_MARKET,OPEN_PRICE,CLOSED_PRICE,HIGH_PRICE,LOW_PRICE,CREATED_AT,UPDATED_AT
103,000020,동화약품,KR7000020008,2153,S,1,1,1,1,1,1,1,1,1
104,000040,KR모터스,KR7000040006,341,S,1,1,1,1,1,1,1,1,1
105,000050,경방,KR7000050005,1732,S,1,1,1,1,1,1,1,1,1
106,000070,삼양홀딩스,KR7000070003,6774,S,1,1,1,1,1,1,1,1,1
107,000075,삼양홀딩스우,KR7000071001,172,S,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1737,479880,한국제15호스팩,KR7479880007,139,S,1,1,1,1,1,1,1,1,1
1738,481890,엔에이치스팩31호,KR7481890002,128,S,1,1,1,1,1,1,1,1,1
1739,482520,교보16호스팩,KR7482520004,124,S,1,1,1,1,1,1,1,1,1
1740,482680,미래에셋비전스팩7호,KR7482680006,163,S,1,1,1,1,1,1,1,1,1
1741,486630,KB제30호스팩,KR7486630007,106,S,1,1,1,1,1,1,1,1,1

In [16]:
combined_symbols

,SHORT_CODE,STOCK_NAME,STANDARD_CODE,MARKET_CAPITALIZATION,STOCK_TRADE_STATUS,STOCK_ID,SUB_CATEGORY_ID,STOCK_EXCHANGE_MARKET,OPEN_PRICE,CLOSED_PRICE,HIGH_PRICE,LOW_PRICE,CREATED_AT,UPDATED_AT
103,000020,동화약품,KR7000020008,2153,S,1,1,1,1,1,1,1,1,1
104,000040,KR모터스,KR7000040006,341,S,1,1,1,1,1,1,1,1,1
105,000050,경방,KR7000050005,1732,S,1,1,1,1,1,1,1,1,1
106,000070,삼양홀딩스,KR7000070003,6774,S,1,1,1,1,1,1,1,1,1
107,000075,삼양홀딩스우,KR7000071001,172,S,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1737,479880,한국제15호스팩,KR7479880007,139,S,1,1,1,1,1,1,1,1,1
1738,481890,엔에이치스팩31호,KR7481890002,128,S,1,1,1,1,1,1,1,1,1
1739,482520,교보16호스팩,KR7482520004,124,S,1,1,1,1,1,1,1,1,1
1740,482680,미래에셋비전스팩7호,KR7482680006,163,S,1,1,1,1,1,1,1,1,1
1741,486630,KB제30호스팩,KR7486630007,106,S,1,1,1,1,1,1,1,1,1

In [21]:
dtype_mapping = {
    'SHORT_CODE': 'str',        # MySQL VARCHAR
    'SUB_CATEGORY_ID': 'int64', # MySQL INT
    'STOCK_NAME': 'str',        # MySQL VARCHAR
    'STANDARD_CODE': 'str',     # MySQL VARCHAR
    'STOCK_EXCHANGE_MARKET': 'str',  # MySQL CHAR(1)
    'MARKET_CAPITALIZATION': 'int64',  # MySQL DOUBLE
    'OPEN_PRICE': 'int64',
    'CLOSED_PRICE': 'int64',
    'HIGH_PRICE': 'int64',
    'LOW_PRICE': 'int64',
    'STOCK_TRADE_STATUS': 'str', # MySQL VARCHAR
}

for column, dtype in dtype_mapping.items():
    combined_symbols[column] = combined_symbols[column].astype(dtype)

# DB에 존재하는 컬럼과 일치하는 컬럼만 선택
filtered_df = combined_symbols[db_columns]

# DataFrame의 500번째부터 1000번째 행까지 선택
subset_df = filtered_df.iloc[500:1000]

In [22]:
subset_df

,STOCK_ID,SHORT_CODE,SUB_CATEGORY_ID,STOCK_NAME,STANDARD_CODE,STOCK_EXCHANGE_MARKET,MARKET_CAPITALIZATION,OPEN_PRICE,CLOSED_PRICE,HIGH_PRICE,LOW_PRICE,STOCK_TRADE_STATUS,CREATED_AT,UPDATED_AT
603,1,016800,1,퍼시스,KR7016800005,1,4772,1,1,1,1,S,1,1
604,1,016880,1,웅진,KR7016880007,1,767,1,1,1,1,S,1,1
605,1,017040,1,광명전기,KR7017040007,1,771,1,1,1,1,S,1,1
606,1,017180,1,명문제약,KR7017180001,1,763,1,1,1,1,S,1,1
607,1,017370,1,우신시스템,KR7017370008,1,1170,1,1,1,1,S,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74,1,014190,1,원익큐브,KR7014190003,1,597,1,1,1,1,S,1,1
75,1,014200,1,광림,KR7014200000,1,912,1,1,1,1,A,1,1
76,1,014470,1,부방,KR7014470009,1,1046,1,1,1,1,S,1,1
77,1,014570,1,고려제약,KR7014570006,1,562,1,1,1,1,S,1,1
78,1,014620,1,성광벤드,KR7014620009,1,4181,1,1,1,1,S,1,1

In [20]:
# combined_symbols DataFrame을 데이터베이스 테이블에 삽입


insert_sql = """
    INSERT INTO STOCK (SHORT_CODE, SUB_CATEGORY_ID, STOCK_NAME, STANDARD_CODE, 
                       STOCK_EXCHANGE_MARKET, MARKET_CAPITALIZATION, OPEN_PRICE, CLOSED_PRICE, 
                       HIGH_PRICE, LOW_PRICE, STOCK_TRADE_STATUS)
    VALUES (%s, %d, %s, %s, %s, %d, %d, %d, %d, %d, %s)
"""

# 각 행의 데이터를 튜플로 변환하여 삽입
values = [tuple(row) for row in subset_df.values]

values

[(1, '016800', 1, '퍼시스', 'KR7016800005', '1', 4772, 1, 1, 1, 1, 'S', 1, 1),
 (1, '016880', 1, '웅진', 'KR7016880007', '1', 767, 1, 1, 1, 1, 'S', 1, 1),
 (1, '017040', 1, '광명전기', 'KR7017040007', '1', 771, 1, 1, 1, 1, 'S', 1, 1),
 (1, '017180', 1, '명문제약', 'KR7017180001', '1', 763, 1, 1, 1, 1, 'S', 1, 1),
 (1, '017370', 1, '우신시스템', 'KR7017370008', '1', 1170, 1, 1, 1, 1, 'S', 1, 1),
 (1, '017390', 1, '서울가스', 'KR7017390006', '1', 2675, 1, 1, 1, 1, 'S', 1, 1),
 (1, '017550', 1, '수산중공업', 'KR7017550005', '1', 1063, 1, 1, 1, 1, 'S', 1, 1),
 (1, '017670', 1, 'SK텔레콤', 'KR7017670001', '1', 122645, 1, 1, 1, 1, 'S', 1, 1),
 (1, '017800', 1, '현대엘리베이', 'KR7017800004', '1', 17024, 1, 1, 1, 1, 'S', 1, 1),
 (1, '017810', 1, '풀무원', 'KR7017810003', '1', 4132, 1, 1, 1, 1, 'S', 1, 1),
 (1, '017860', 1, 'DS단석', 'KR7017860008', '1', 4483, 1, 1, 1, 1, 'S', 1, 1),
 (1, '017900', 1, '광전자', 'KR7017900002', '1', 1091, 1, 1, 1, 1, 'S', 1, 1),
 (1, '017940', 1, 'E1', 'KR7017940008', '1', 5172, 1, 1, 1, 1, 'S', 1, 1),
 (1, '017960', 1, '한국카본', 'KR7017960006', '1', 5876, 1, 1, 1, 1, 'S', 1, 1),
 (1, '018250', 1, '애경산업', 'KR7018250001', '1', 4928, 1, 1, 1, 1, 'S', 1, 1),
 (1,
  '018260',
  1,
  '삼성에스디에스',
  'KR7018260000',
  '1',
  118697,
  1,
  1,
  1,
  1,
  'S',
  1,
  1),
 (1, '018470', 1, '조일알미늄', 'KR7018470005', '1', 2093, 1, 1, 1, 1, 'S', 1, 1),
 (1, '018500', 1, '동원금속', 'KR7018500009', '1', 656, 1, 1, 1, 1, 'S', 1, 1),
 (1, '018670', 1, 'SK가스', 'KR7018670000', '1', 15737, 1, 1, 1, 1, 'S', 1, 1),
 (1, '018880', 1, '한온시스템', 'KR7018880005', '1', 22072, 1, 1, 1, 1, 'S', 1, 1),
 (1, '019170', 1, '신풍제약', 'KR7019170000', '1', 6495, 1, 1, 1, 1, 'S', 1, 1),
 (1, '019175', 1, '신풍제약우', 'KR7019171008', '1', 431, 1, 1, 1, 1, 'S', 1, 1),
 (1, '019180', 1, '티에이치엔', 'KR7019180009', '1', 612, 1, 1, 1, 1, 'S', 1, 1),
 (1, '019440', 1, '세아특수강', 'KR7019440007', '1', 1180, 1, 1, 1, 1, 'S', 1, 1),
 (1, '019490', 1, '하이트론', 'KR7019490002', '1', 1165, 1, 1, 1, 1, 'S', 1, 1),
 (1, '019680', 1, '대교', 'KR7019680008', '1', 1897, 1, 1, 1, 1, 'S', 1, 1),
 (1, '019685', 1, '대교우B', 'KR7019681006', '1', 262, 1, 1, 1, 1, 'S', 1, 1),
 (1, '020000', 1, '한섬', 'KR7020000006', '1', 3799, 1, 1, 1, 1, 'S', 1, 1),
 (1, '020120', 1, '키다리스튜디오', 'KR7020120002', '1', 1315, 1, 1, 1, 1, 'S', 1, 1),
 (1,
  '020150',
  1,
  '롯데에너지머티리얼즈',
  'KR7020150009',
  '1',
  18951,
  1,
  1,
  1,
  1,
  'S',
  1,
  1),
 (1, '020560', 1, '아시아나항공', 'KR7020560009', '1', 7061, 1, 1, 1, 1, 'S', 1, 1),
 (1, '020760', 1, '일진디스플', 'KR7020760005', '1', 518, 1, 1, 1, 1, 'S', 1, 1),
 (1, '021050', 1, '서원', 'KR7021050000', '1', 613, 1, 1, 1, 1, 'S', 1, 1),
 (1, '021240', 1, '코웨이', 'KR7021240007', '1', 50405, 1, 1, 1, 1, 'S', 1, 1),
 (1, '021820', 1, '세원정공', 'KR7021820006', '1', 787, 1, 1, 1, 1, 'S', 1, 1),
 (1, '022100', 1, '포스코DX', 'KR7022100002', '1', 47662, 1, 1, 1, 1, 'S', 1, 1),
 (1, '023000', 1, '삼원강재', 'KR7023000003', '1', 1036, 1, 1, 1, 1, 'S', 1, 1),
 (1, '023150', 1, 'MH에탄올', 'KR7023150006', '1', 451, 1, 1, 1, 1, 'S', 1, 1),
 (1, '023350', 1, '한국종합기술', 'KR7023350002', '1', 514, 1, 1, 1, 1, 'S', 1, 1),
 (1, '023450', 1, '동남합성', 'KR7023450000', '1', 1183, 1, 1, 1, 1, 'S', 1, 1),
 (1, '023530', 1, '롯데쇼핑', 'KR7023530009', '1', 17595, 1, 1, 1, 1, 'S', 1, 1),
 (1, '023590', 1, '다우기술', 'KR7023590003', '1', 8174, 1, 1, 1, 1, 'S', 1, 1),
 (1, '023800', 1, '인지컨트롤스', 'KR7023800006', '1', 981, 1, 1, 1, 1, 'S', 1, 1),
 (1, '023810', 1, '인팩', 'KR7023810005', '1', 804, 1, 1, 1, 1, 'S', 1, 1),
 (1, '023960', 1, '에쓰씨엔지니어링', 'KR7023960008', '1', 548, 1, 1, 1, 1, 'S', 1, 1),
 (1, '024070', 1, 'WISCOM', 'KR7024070005', '1', 319, 1, 1, 1, 1, 'S', 1, 1),
 (1, '024090', 1, '디씨엠', 'KR7024090003', '1', 1431, 1, 1, 1, 1, 'S', 1, 1),
 (1, '024110', 1, '기업은행', 'KR7024110009', '1', 110682, 1, 1, 1, 1, 'S', 1, 1),
 (1, '024720', 1, '콜마홀딩스', 'KR7024720005', '1', 2678, 1, 1, 1, 1, 'S', 1, 1),
 (1, '024890', 1, '대원화성', 'KR7024890006', '1', 510, 1, 1, 1, 1, 'S', 1, 1),
 (1, '024900', 1, '덕양산업', 'KR7024900003', '1', 1217, 1, 1, 1, 1, 'S', 1, 1),
 (1, '025000', 1, 'KPX케미칼', 'KR7025000001', '1', 2311, 1, 1, 1, 1, 'S', 1, 1),
 (1, '025530', 1, 'SJM홀딩스', 'KR7025530007', '1', 534, 1, 1, 1, 1, 'S', 1, 1),
 (1, '025540', 1, '한국단자', 'KR7025540006', '1', 7436, 1, 1, 1, 1, 'S', 1, 1),
 (1, '025560', 1, '미래산업', 'KR7025560004', '1', 396, 1, 1, 1, 1, 'S', 1, 1),
 (1, '025620', 1, '제이준코스메틱', 'KR7025620006', '1', 249, 1, 1, 1, 1, 'S', 1, 1),
 (1, '025750', 1, '한솔홈데코', 'KR7025750001', '1', 586, 1, 1, 1, 1, 'S', 1, 1),
 (1, '025820', 1, '이구산업', 'KR7025820002', '1', 1628, 1, 1, 1, 1, 'S', 1, 1),
 (1, '025860', 1, '남해화학', 'KR7025860008', '1', 3214, 1, 1, 1, 1, 'S', 1, 1),
 (1, '025890', 1, '한국주강', 'KR7025890005', '1', 223, 1, 1, 1, 1, 'S', 1, 1),
 (1,
  '026890',
  1,
  '스틱인베스트먼트',
  'KR7026890004',
  '1',
  3384,
  1,
  1,
  1,
  1,
  'S',
  1,
  1),
 (1, '026940', 1, '부국철강', 'KR7026940007', '1', 523, 1, 1, 1, 1, 'S', 1, 1),
 (1, '026960', 1, '동서', 'KR7026960005', '1', 19232, 1, 1, 1, 1, 'S', 1, 1),
 (1, '027410', 1, 'BGF', 'KR7027410000', '1', 3383, 1, 1, 1, 1, 'S', 1, 1),
 (1, '027740', 1, '마니커', 'KR7027740000', '1', 601, 1, 1, 1, 1, 'S', 1, 1),
 (1, '027970', 1, '한국제지', 'KR7027970003', '1', 2027, 1, 1, 1, 1, 'S', 1, 1),
 (1, '028050', 1, '삼성E&A', 'KR7028050003', '1', 47334, 1, 1, 1, 1, 'S', 1, 1),
 (1, '028100', 1, '동아지질', 'KR7028100006', '1', 1742, 1, 1, 1, 1, 'S', 1, 1),
 (1, '028260', 1, '삼성물산', 'KR7028260008', '1', 246230, 1, 1, 1, 1, 'S', 1, 1),
 (1, '02826K', 1, '삼성물산우B', 'KR702826K016', '1', 1514, 1, 1, 1, 1, 'S', 1, 1),
 (1, '028670', 1, '팬오션', 'KR7028670008', '1', 20367, 1, 1, 1, 1, 'S', 1, 1),
 (1, '029460', 1, '케이씨', 'KR7029460003', '1', 2690, 1, 1, 1, 1, 'S', 1, 1),
 (1, '029530', 1, '신도리코', 'KR7029530003', '1', 4062, 1, 1, 1, 1, 'S', 1, 1),
 (1, '029780', 1, '삼성카드', 'KR7029780004', '1', 46691, 1, 1, 1, 1, 'S', 1, 1),
 (1, '030000', 1, '제일기획', 'KR7030000004', '1', 21052, 1, 1, 1, 1, 'S', 1, 1),
 (1,
  '030190',
  1,
  'NICE평가정보',
  'KR7030190003',
  '1',
  6281,
  1,
  1,
  1,
  1,
  'S',
  1,
  1),
 (1, '030200', 1, 'KT', 'KR7030200000', '1', 102068, 1, 1, 1, 1, 'S', 1, 1),
 (1, '030210', 1, '다올투자증권', 'KR7030210009', '1', 1842, 1, 1, 1, 1, 'S', 1, 1),
 (1, '030610', 1, '교보증권', 'KR7030610000', '1', 6131, 1, 1, 1, 1, 'S', 1, 1),
 (1, '030720', 1, '동원수산', 'KR7030720007', '1', 275, 1, 1, 1, 1, 'S', 1, 1),
 (1,
  '031430',
  1,
  '신세계인터내셔날',
  'KR7031430002',
  '1',
  4755,
  1,
  1,
  1,
  1,
  'S',
  1,
  1),
 (1, '031440', 1, '신세계푸드', 'KR7031440001', '1', 1372, 1, 1, 1, 1, 'S', 1, 1),
 (1, '031820', 1, '콤텍시스템', 'KR7031820004', '1', 699, 1, 1, 1, 1, 'S', 1, 1),
 (1, '032350', 1, '롯데관광개발', 'KR7032350001', '1', 7177, 1, 1, 1, 1, 'S', 1, 1),
 (1, '032560', 1, '황금에스티', 'KR7032560005', '1', 945, 1, 1, 1, 1, 'S', 1, 1),
 (1, '032640', 1, 'LG유플러스', 'KR7032640005', '1', 42831, 1, 1, 1, 1, 'S', 1, 1),
 (1, '032830', 1, '삼성생명', 'KR7032830002', '1', 187200, 1, 1, 1, 1, 'S', 1, 1),
 (1, '033180', 1, 'KH 필룩스', 'KR7033180001', '1', 1253, 1, 1, 1, 1, 'A', 1, 1),
 (1, '033240', 1, '자화전자', 'KR7033240003', '1', 3868, 1, 1, 1, 1, 'S', 1, 1),
 (1, '033250', 1, '체시스', 'KR7033250002', '1', 427, 1, 1, 1, 1, 'S', 1, 1),
 (1, '033270', 1, '유나이티드제약', 'KR7033270000', '1', 3519, 1, 1, 1, 1, 'S', 1, 1),
 (1, '033530', 1, 'SJG세종', 'KR7033530007', '1', 1343, 1, 1, 1, 1, 'S', 1, 1),
 (1, '033780', 1, 'KT&G', 'KR7033780008', '1', 141139, 1, 1, 1, 1, 'S', 1, 1),
 (1, '033920', 1, '무학', 'KR7033920000', '1', 1755, 1, 1, 1, 1, 'S', 1, 1),
 (1,
  '034020',
  1,
  '두산에너빌리티',
  'KR7034020008',
  '1',
  115941,
  1,
  1,
  1,
  1,
  'S',
  1,
  1),
 (1, '034120', 1, 'SBS', 'KR7034120006', '1', 2845, 1, 1, 1, 1, 'S', 1, 1),
 (1,
  '034220',
  1,
  'LG디스플레이',
  'KR7034220004',
  '1',
  54400,
  1,
  1,
  1,
  1,
  'S',
  1,
  1),
 (1, '034230', 1, '파라다이스', 'KR7034230003', '1', 10250, 1, 1, 1, 1, 'S', 1, 1),
 (1, '034300', 1, '신세계건설', 'KR7034300004', '1', 1147, 1, 1, 1, 1, 'S', 1, 1),
 (1, '034310', 1, 'NICE', 'KR7034310003', '1', 4035, 1, 1, 1, 1, 'S', 1, 1),
 (1, '034590', 1, '인천도시가스', 'KR7034590000', '1', 1117, 1, 1, 1, 1, 'S', 1, 1),
 (1, '034730', 1, 'SK', 'KR7034730002', '1', 109841, 1, 1, 1, 1, 'S', 1, 1),
 (1, '03473K', 1, 'SK우', 'KR703473K016', '1', 713, 1, 1, 1, 1, 'S', 1, 1),
 (1, '034830', 1, '한국토지신탁', 'KR7034830000', '1', 2608, 1, 1, 1, 1, 'S', 1, 1),
 (1, '035000', 1, 'HS애드', 'KR7035000009', '1', 1055, 1, 1, 1, 1, 'S', 1, 1),
 (1, '035150', 1, '백산', 'KR7035150002', '1', 3096, 1, 1, 1, 1, 'S', 1, 1),
 (1, '035250', 1, '강원랜드', 'KR7035250000', '1', 36583, 1, 1, 1, 1, 'S', 1, 1),
 (1, '035420', 1, 'NAVER', 'KR7035420009', '1', 267223, 1, 1, 1, 1, 'S', 1, 1),
 (1, '035510', 1, '신세계 I&C', 'KR7035510007', '1', 1577, 1, 1, 1, 1, 'S', 1, 1),
 (1, '035720', 1, '카카오', 'KR7035720002', '1', 159004, 1, 1, 1, 1, 'S', 1, 1),
 (1, '036420', 1, '콘텐트리중앙', 'KR7036420008', '1', 1953, 1, 1, 1, 1, 'S', 1, 1),
 (1, '036460', 1, '한국가스공사', 'KR7036460004', '1', 42787, 1, 1, 1, 1, 'S', 1, 1),
 (1, '036530', 1, 'SNT홀딩스', 'KR7036530004', '1', 3660, 1, 1, 1, 1, 'S', 1, 1),
 (1, '036570', 1, '엔씨소프트', 'KR7036570000', '1', 43578, 1, 1, 1, 1, 'S', 1, 1),
 (1, '036580', 1, '팜스코', 'KR7036580009', '1', 844, 1, 1, 1, 1, 'S', 1, 1),
 (1, '037270', 1, 'YG PLUS', 'KR7037270006', '1', 1645, 1, 1, 1, 1, 'S', 1, 1),
 (1, '037560', 1, 'LG헬로비전', 'KR7037560000', '1', 2052, 1, 1, 1, 1, 'S', 1, 1),
 (1, '037710', 1, '광주신세계', 'KR7037710001', '1', 2339, 1, 1, 1, 1, 'S', 1, 1),
 (1, '039130', 1, '하나투어', 'KR7039130000', '1', 7754, 1, 1, 1, 1, 'S', 1, 1),
 (1, '039490', 1, '키움증권', 'KR7039490008', '1', 33337, 1, 1, 1, 1, 'S', 1, 1),
 (1, '039570', 1, 'HDC랩스', 'KR7039570007', '1', 2081, 1, 1, 1, 1, 'S', 1, 1),
 (1, '041650', 1, '상신브레이크', 'KR7041650003', '1', 743, 1, 1, 1, 1, 'S', 1, 1),
 (1, '042660', 1, '한화오션', 'KR7042660001', '1', 98358, 1, 1, 1, 1, 'S', 1, 1),
 (1,
  '042670',
  1,
  'HD현대인프라코어',
  'KR7042670000',
  '1',
  14333,
  1,
  1,
  1,
  1,
  'S',
  1,
  1),
 (1, '042700', 1, '한미반도체', 'KR7042700005', '1', 103395, 1, 1, 1, 1, 'S', 1, 1),
 (1, '044380', 1, '주연테크', 'KR7044380004', '1', 220, 1, 1, 1, 1, 'S', 1, 1),
 (1, '044450', 1, 'KSS해운', 'KR7044450005', '1', 2165, 1, 1, 1, 1, 'S', 1, 1),
 (1, '044820', 1, '코스맥스비티아이', 'KR7044820009', '1', 835, 1, 1, 1, 1, 'S', 1, 1),
 (1, '047040', 1, '대우건설', 'KR7047040001', '1', 16209, 1, 1, 1, 1, 'S', 1, 1),
 (1,
  '047050',
  1,
  '포스코인터내셔널',
  'KR7047050000',
  '1',
  97285,
  1,
  1,
  1,
  1,
  'S',
  1,
  1),
 (1, '047400', 1, '유니온머티리얼', 'KR7047400007', '1', 913, 1, 1, 1, 1, 'S', 1, 1),
 (1, '047810', 1, '한국항공우주', 'KR7047810007', '1', 52831, 1, 1, 1, 1, 'S', 1, 1),
 (1, '049770', 1, '동원F&B', 'KR7049770001', '1', 6280, 1, 1, 1, 1, 'S', 1, 1),
 (1, '049800', 1, '우진플라임', 'KR7049800006', '1', 452, 1, 1, 1, 1, 'S', 1, 1),
 (1, '051600', 1, '한전KPS', 'KR7051600005', '1', 18810, 1, 1, 1, 1, 'S', 1, 1),
 (1, '051630', 1, '진양화학', 'KR7051630002', '1', 477, 1, 1, 1, 1, 'S', 1, 1),
 (1, '051900', 1, 'LG생활건강', 'KR7051900009', '1', 58412, 1, 1, 1, 1, 'S', 1, 1),
 (1, '051905', 1, 'LG생활건강우', 'KR7051901007', '1', 3338, 1, 1, 1, 1, 'S', 1, 1),
 (1, '051910', 1, 'LG화학', 'KR7051910008', '1', 246014, 1, 1, 1, 1, 'S', 1, 1),
 (1, '051915', 1, 'LG화학우', 'KR7051911006', '1', 18453, 1, 1, 1, 1, 'S', 1, 1),
 (1, '052690', 1, '한전기술', 'KR7052690005', '1', 25951, 1, 1, 1, 1, 'S', 1, 1),
 (1, '053210', 1, '스카이라이프', 'KR7053210001', '1', 2369, 1, 1, 1, 1, 'S', 1, 1),
 (1, '053690', 1, '한미글로벌', 'KR7053690004', '1', 1612, 1, 1, 1, 1, 'S', 1, 1),
 (1, '055490', 1, '테이팩스', 'KR7055490007', '1', 895, 1, 1, 1, 1, 'S', 1, 1),
 (1, '055550', 1, '신한지주', 'KR7055550008', '1', 272525, 1, 1, 1, 1, 'S', 1, 1),
 (1, '057050', 1, '현대홈쇼핑', 'KR7057050007', '1', 5628, 1, 1, 1, 1, 'S', 1, 1),
 (1, '058430', 1, '포스코스틸리온', 'KR7058430000', '1', 2481, 1, 1, 1, 1, 'S', 1, 1),
 (1, '058650', 1, '세아홀딩스', 'KR7058650003', '1', 4068, 1, 1, 1, 1, 'S', 1, 1),
 (1, '058730', 1, '다스코', 'KR7058730003', '1', 600, 1, 1, 1, 1, 'S', 1, 1),
 (1, '058850', 1, 'KTcs', 'KR7058850009', '1', 1143, 1, 1, 1, 1, 'S', 1, 1),
 (1, '058860', 1, 'KTis', 'KR7058860008', '1', 901, 1, 1, 1, 1, 'S', 1, 1),
 (1, '060980', 1, 'HL홀딩스', 'KR7060980000', '1', 3559, 1, 1, 1, 1, 'S', 1, 1),
 (1, '062040', 1, '산일전기', 'KR7062040001', '1', 14157, 1, 1, 1, 1, 'S', 1, 1),
 (1, '063160', 1, '종근당바이오', 'KR7063160006', '1', 1577, 1, 1, 1, 1, 'S', 1, 1),
 (1, '064350', 1, '현대로템', 'KR7064350002', '1', 60792, 1, 1, 1, 1, 'S', 1, 1),
 (1, '064960', 1, 'SNT모티브', 'KR7064960008', '1', 7179, 1, 1, 1, 1, 'S', 1, 1),
 (1, '066570', 1, 'LG전자', 'KR7066570003', '1', 172812, 1, 1, 1, 1, 'S', 1, 1),
 (1, '066575', 1, 'LG전자우', 'KR7066571001', '1', 8489, 1, 1, 1, 1, 'S', 1, 1),
 (1, '066970', 1, '엘앤에프', 'KR7066970005', '1', 37929, 1, 1, 1, 1, 'S', 1, 1),
 (1, '067830', 1, '세이브존I&C', 'KR7067830000', '1', 851, 1, 1, 1, 1, 'S', 1, 1),
 (1, '068270', 1, '셀트리온', 'KR7068270008', '1', 434042, 1, 1, 1, 1, 'S', 1, 1),
 (1, '068290', 1, '삼성출판사', 'KR7068290006', '1', 1545, 1, 1, 1, 1, 'S', 1, 1),
 (1, '069260', 1, 'TKG휴켐스', 'KR7069260008', '1', 7828, 1, 1, 1, 1, 'S', 1, 1),
 (1, '069460', 1, '대호에이엘', 'KR7069460004', '1', 857, 1, 1, 1, 1, 'S', 1, 1),
 (1, '069620', 1, '대웅제약', 'KR7069620003', '1', 16232, 1, 1, 1, 1, 'S', 1, 1),
 (1, '069640', 1, '한세엠케이', 'KR7069640001', '1', 524, 1, 1, 1, 1, 'S', 1, 1),
 (1, '069730', 1, 'DSR제강', 'KR7069730000', '1', 547, 1, 1, 1, 1, 'S', 1, 1),
 (1, '069960', 1, '현대백화점', 'KR7069960003', '1', 11186, 1, 1, 1, 1, 'S', 1, 1),
 (1, '070960', 1, '모나용평', 'KR7070960000', '1', 2055, 1, 1, 1, 1, 'S', 1, 1),
 (1, '071050', 1, '한국금융지주', 'KR7071050009', '1', 40178, 1, 1, 1, 1, 'S', 1, 1),
 (1, '071055', 1, '한국금융지주우', 'KR7071051007', '1', 2964, 1, 1, 1, 1, 'S', 1, 1),
 (1, '071090', 1, '하이스틸', 'KR7071090005', '1', 668, 1, 1, 1, 1, 'S', 1, 1),
 (1, '071320', 1, '지역난방공사', 'KR7071320006', '1', 5360, 1, 1, 1, 1, 'S', 1, 1),
 (1, '071840', 1, '롯데하이마트', 'KR7071840003', '1', 1919, 1, 1, 1, 1, 'S', 1, 1),
 (1, '071950', 1, '코아스', 'KR7071950000', '1', 352, 1, 1, 1, 1, 'A', 1, 1),
 (1,
  '071970',
  1,
  'HD현대마린엔진',
  'KR7071970008',
  '1',
  6356,
  1,
  1,
  1,
  1,
  'S',
  1,
  1),
 (1, '072130', 1, '유엔젤', 'KR7072130008', '1', 527, 1, 1, 1, 1, 'S', 1, 1),
 (1, '072710', 1, '농심홀딩스', 'KR7072710007', '1', 3098, 1, 1, 1, 1, 'S', 1, 1),
 (1, '073240', 1, '금호타이어', 'KR7073240004', '1', 12955, 1, 1, 1, 1, 'S', 1, 1),
 (1, '074610', 1, '이엔플러스', 'KR7074610007', '1', 1215, 1, 1, 1, 1, 'S', 1, 1),
 (1, '075180', 1, '새론오토모티브', 'KR7075180000', '1', 738, 1, 1, 1, 1, 'S', 1, 1),
 (1, '075580', 1, '세진중공업', 'KR7075580001', '1', 4240, 1, 1, 1, 1, 'S', 1, 1),
 (1, '077500', 1, '유니퀘스트', 'KR7077500007', '1', 1002, 1, 1, 1, 1, 'S', 1, 1),
 (1, '077970', 1, 'STX엔진', 'KR7077970002', '1', 4178, 1, 1, 1, 1, 'S', 1, 1),
 (1, '078000', 1, '텔코웨어', 'KR7078000007', '1', 924, 1, 1, 1, 1, 'S', 1, 1),
 (1, '078520', 1, '에이블씨엔씨', 'KR7078520004', '1', 1940, 1, 1, 1, 1, 'S', 1, 1),
 (1, '078930', 1, 'GS', 'KR7078930005', '1', 39860, 1, 1, 1, 1, 'S', 1, 1),
 (1, '078935', 1, 'GS우', 'KR7078931003', '1', 729, 1, 1, 1, 1, 'S', 1, 1),
 (1, '079160', 1, 'CJ CGV', 'KR7079160008', '1', 9835, 1, 1, 1, 1, 'S', 1, 1),
 (1, '079430', 1, '현대리바트', 'KR7079430005', '1', 1665, 1, 1, 1, 1, 'S', 1, 1),
 (1, '079550', 1, 'LIG넥스원', 'KR7079550000', '1', 48620, 1, 1, 1, 1, 'S', 1, 1),
 (1, '079900', 1, '전진건설로봇', 'KR7079900007', '1', 2426, 1, 1, 1, 1, 'S', 1, 1),
 (1, '079980', 1, '휴비스', 'KR7079980009', '1', 1029, 1, 1, 1, 1, 'S', 1, 1),
 (1, '081000', 1, '일진다이아', 'KR7081000002', '1', 1857, 1, 1, 1, 1, 'S', 1, 1),
 (1, '081660', 1, '휠라홀딩스', 'KR7081660003', '1', 26171, 1, 1, 1, 1, 'S', 1, 1),
 (1, '082640', 1, '동양생명', 'KR7082640004', '1', 8794, 1, 1, 1, 1, 'S', 1, 1),
 (1, '082740', 1, '한화엔진', 'KR7082740002', '1', 11248, 1, 1, 1, 1, 'S', 1, 1),
 (1, '083420', 1, '그린케미칼', 'KR7083420000', '1', 1579, 1, 1, 1, 1, 'S', 1, 1),
 (1, '084010', 1, '대한제강', 'KR7084010008', '1', 3050, 1, 1, 1, 1, 'S', 1, 1),
 (1, '084670', 1, '동양고속', 'KR7084670009', '1', 253, 1, 1, 1, 1, 'S', 1, 1),
 (1, '084680', 1, '이월드', 'KR7084680008', '1', 2426, 1, 1, 1, 1, 'S', 1, 1),
 (1, '084690', 1, '대상홀딩스', 'KR7084690007', '1', 3204, 1, 1, 1, 1, 'S', 1, 1),
 (1, '084695', 1, '대상홀딩스우', 'KR7084691005', '1', 186, 1, 1, 1, 1, 'S', 1, 1),
 (1, '084870', 1, 'TBH글로벌', 'KR7084870005', '1', 304, 1, 1, 1, 1, 'S', 1, 1),
 (1, '085310', 1, '엔케이', 'KR7085310001', '1', 635, 1, 1, 1, 1, 'S', 1, 1),
 (1, '085620', 1, '미래에셋생명', 'KR7085620003', '1', 9275, 1, 1, 1, 1, 'S', 1, 1),
 (1, '086280', 1, '현대글로비스', 'KR7086280005', '1', 88050, 1, 1, 1, 1, 'S', 1, 1),
 (1,
  '086790',
  1,
  '하나금융지주',
  'KR7086790003',
  '1',
  165737,
  1,
  1,
  1,
  1,
  'S',
  1,
  1),
 (1, '088350', 1, '한화생명', 'KR7088350004', '1', 24926, 1, 1, 1, 1, 'S', 1, 1),
 (1, '088790', 1, '진도', 'KR7088790001', '1', 232, 1, 1, 1, 1, 'S', 1, 1),
 (1, '089470', 1, 'HDC현대EP', 'KR7089470009', '1', 1357, 1, 1, 1, 1, 'S', 1, 1),
 (1, '089590', 1, '제주항공', 'KR7089590004', '1', 7249, 1, 1, 1, 1, 'S', 1, 1),
 (1, '089860', 1, '롯데렌탈', 'KR7089860001', '1', 11521, 1, 1, 1, 1, 'S', 1, 1),
 (1, '090080', 1, '평화산업', 'KR7090080003', '1', 556, 1, 1, 1, 1, 'S', 1, 1),
 (1, '090350', 1, '노루페인트', 'KR7090350000', '1', 1758, 1, 1, 1, 1, 'S', 1, 1),
 (1, '090355', 1, '노루페인트우', 'KR7090351008', '1', 65, 1, 1, 1, 1, 'S', 1, 1),
 (1, '090370', 1, '메타랩스', 'KR7090370008', '1', 405, 1, 1, 1, 1, 'S', 1, 1),
 (1, '090430', 1, '아모레퍼시픽', 'KR7090430000', '1', 88148, 1, 1, 1, 1, 'S', 1, 1),
 (1, '090435', 1, '아모레퍼시픽우', 'KR7090431008', '1', 4159, 1, 1, 1, 1, 'S', 1, 1),
 (1, '090460', 1, '비에이치', 'KR7090460007', '1', 6231, 1, 1, 1, 1, 'S', 1, 1),
 (1, '091090', 1, '세원이앤씨', 'KR7091090001', '1', 548, 1, 1, 1, 1, 'A', 1, 1),
 (1, '091810', 1, '티웨이항공', 'KR7091810002', '1', 6116, 1, 1, 1, 1, 'S', 1, 1),
 (1, '092200', 1, '디아이씨', 'KR7092200005', '1', 1571, 1, 1, 1, 1, 'S', 1, 1),
 (1, '092220', 1, 'KEC', 'KR7092220003', '1', 1955, 1, 1, 1, 1, 'S', 1, 1),
 (1, '092230', 1, 'KPX홀딩스', 'KR7092230002', '1', 2429, 1, 1, 1, 1, 'S', 1, 1),
 (1, '092440', 1, '기신정기', 'KR7092440007', '1', 769, 1, 1, 1, 1, 'S', 1, 1),
 (1, '092780', 1, '동양피스톤', 'KR7092780006', '1', 770, 1, 1, 1, 1, 'S', 1, 1),
 (1, '092790', 1, '넥스틸', 'KR7092790005', '1', 2080, 1, 1, 1, 1, 'S', 1, 1),
 (1, '093050', 1, 'LF', 'KR7093050003', '1', 4298, 1, 1, 1, 1, 'S', 1, 1),
 (1, '093230', 1, '이아이디', 'KR7093230001', '1', 3541, 1, 1, 1, 1, 'A', 1, 1),
 (1, '093240', 1, '형지엘리트', 'KR7093240000', '1', 680, 1, 1, 1, 1, 'S', 1, 1),
 (1, '093370', 1, '후성', 'KR7093370005', '1', 6917, 1, 1, 1, 1, 'S', 1, 1),
 (1, '094280', 1, '효성ITX', 'KR7094280005', '1', 1503, 1, 1, 1, 1, 'S', 1, 1),
 (1, '095570', 1, 'AJ네트웍스', 'KR7095570008', '1', 2151, 1, 1, 1, 1, 'S', 1, 1),
 (1, '095720', 1, '웅진씽크빅', 'KR7095720009', '1', 2045, 1, 1, 1, 1, 'S', 1, 1),
 (1, '096760', 1, 'JW홀딩스', 'KR7096760004', '1', 2310, 1, 1, 1, 1, 'S', 1, 1),
 (1,
  '096770',
  1,
  'SK이노베이션',
  'KR7096770003',
  '1',
  116127,
  1,
  1,
  1,
  1,
  'S',
  1,
  1),
 (1,
  '096775',
  1,
  'SK이노베이션우',
  'KR7096771001',
  '1',
  1022,
  1,
  1,
  1,
  1,
  'S',
  1,
  1),
 (1, '097230', 1, 'HJ중공업', 'KR7097230007', '1', 2248, 1, 1, 1, 1, 'S', 1, 1),
 (1, '097520', 1, '엠씨넥스', 'KR7097520001', '1', 3316, 1, 1, 1, 1, 'S', 1, 1),
 (1, '097950', 1, 'CJ제일제당', 'KR7097950000', '1', 46216, 1, 1, 1, 1, 'S', 1, 1),
 (1,
  '097955',
  1,
  'CJ제일제당 우',
  'KR7097951008',
  '1',
  1830,
  1,
  1,
  1,
  1,
  'S',
  1,
  1),
 (1, '100090', 1, 'SK오션플랜트', 'KR7100090000', '1', 9187, 1, 1, 1, 1, 'S', 1, 1),
 (1, '100220', 1, '비상교육', 'KR7100220003', '1', 658, 1, 1, 1, 1, 'S', 1, 1),
 (1, '100250', 1, '진양홀딩스', 'KR7100250000', '1', 1783, 1, 1, 1, 1, 'S', 1, 1),
 (1, '100840', 1, 'SNT에너지', 'KR7100840008', '1', 2760, 1, 1, 1, 1, 'S', 1, 1),
 (1, '101140', 1, '인바이오젠', 'KR7101140002', '1', 938, 1, 1, 1, 1, 'A', 1, 1),
 (1, '101530', 1, '해태제과식품', 'KR7101530004', '1', 1697, 1, 1, 1, 1, 'S', 1, 1),
 (1, '102260', 1, '동성케미컬', 'KR7102260007', '1', 2111, 1, 1, 1, 1, 'S', 1, 1),
 (1, '102280', 1, '쌍방울', 'KR7102280005', '1', 706, 1, 1, 1, 1, 'A', 1, 1),
 (1, '102460', 1, '이연제약', 'KR7102460003', '1', 2676, 1, 1, 1, 1, 'S', 1, 1),
 (1, '103140', 1, '풍산', 'KR7103140000', '1', 16394, 1, 1, 1, 1, 'S', 1, 1),

In [19]:


try:
    with connection.cursor() as cursor:
        # 여러 개의 레코드를 한 번에 삽입
        cursor.executemany(insert_sql, values)
        
        # 변경 사항을 커밋하여 데이터베이스에 반영
        connection.commit()
        print(f"{cursor.rowcount} rows inserted into STOCK table.")
finally:
    connection.close()
# combined_symbols.iloc[500:502]

TypeError: %d format: a real number is required, not str